version: "3.6"
services:
  k3s:
    image: rancher/k3s:v1.21.3-k3s1
    privileged: true
    command: server
    tmpfs:
      - /run
      - /var/run
    environment:
      K3S_KUBECONFIG_OUTPUT: /output/kubeconfig.yaml
      K3S_KUBECONFIG_MODE: 666
      VIRTUAL_HOST: k3s.127.0.0.1.nip.io
    volumes:
      - ./output/storage:/var/lib/rancher/k3s/storage:Z
      - ./output/configuration:/output
    ports:
      - "6443:6443"
